import { Project, JournalEntry, Exploration } from "./types";

export const projects: Project[] = [
  {
    id: "proj-1",
    title: "LogoMotion AI",
    category: "Next.js / Express / Supabase / AI",
    description: "A full-stack SaaS platform that transforms static logos into professional brand animations using Classic Animations and Structural Motion engines. It includes Google and email authentication, multi-format MP4, GIF, WebM and Lottie exports, Stripe subscriptions, a credit system, asynchronous Redis and BullMQ jobs, Remotion rendering, secure user and admin dashboards, transactional emails and product analytics.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=1200",
    spanClass: "md:col-span-7",
    aspectClass: "aspect-[16/10]",
    link: "#",
    year: "2026",
  },
  {
    id: "proj-2",
    title: "Creatoros",
    category: "React / Node.js / UI/UX",
    description: "A creator-focused digital ecosystem designed to help content creators manage their audience, showcase content, and grow their personal brand through modern web experiences.",
    image: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=1000",
    spanClass: "md:col-span-5",
    aspectClass: "aspect-[4/3]",
    link: "#",
    year: "2025",
  },
  {
    id: "proj-3",
    title: "AgriMétéo",
    category: "React / Express / Supabase / PWA",
    description: "A full-stack smart agriculture platform that centralizes crop planning, contextual weather forecasts and alerts, plant diagnostics, personalized recommendations and community collaboration. It includes Google and email authentication, user profiles, notifications, an installable PWA, secure Supabase storage, Row Level Security, and an administration dashboard with role management, permissions and audit logs.",
    image: "/projects/agrimeteo-banner.png",
    imageFit: "contain",
    imagePosition: "center",
    spanClass: "md:col-span-5",
    aspectClass: "aspect-[4/3]",
    link: "https://agrimeteo.vercel.app/",
    linkLabel: "Live website",
    year: "2026",
  },
  {
    id: "proj-4",
    title: "Portfolio Experiments",
    category: "Python / Framer Motion / Creative Dev",
    description: "A collection of experimental interfaces, animations, and immersive frontend concepts exploring motion design and interactive storytelling.",
    image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=1200",
    spanClass: "md:col-span-7",
    aspectClass: "aspect-[16/10]",
    link: "#",
    year: "2025",
  },
  {
    id: "proj-5",
    title: "Smart Access",
    category: "Django / PostgreSQL / Computer Vision",
    description: "A secure enterprise document access platform with facial recognition authentication, department-based permissions, exceptional access requests and advanced document management. It provides secure file previews and downloads, text editing, version history, audit logs, responsive employee and administrator dashboards, and optional ONLYOFFICE integration using Django, PostgreSQL, JavaScript, face_recognition and OpenCV.",
    image: "/projects/smart-access-banner.png",
    spanClass: "md:col-span-12",
    aspectClass: "aspect-[16/7]",
    link: "https://github.com/Emryc-dev/Smart-Access",
    linkLabel: "GitHub repository",
    year: "2026",
  },
];

export const allProjects: Project[] = [
  ...projects,
  {
    id: "proj-6",
    title: "The Shield Corporation",
    category: "React / TypeScript / Cybersecurity / IT Services",
    description:
      "A professional bilingual website for a cybersecurity, network administration, and IT services company. It presents dedicated service pages for network administration, IT security, pentesting, web audit, cloud computing, secure hosting, cyber consulting, and secure web development. The experience includes responsive layouts, interactive animations, dynamic service cards, animated testimonials, a multilingual chatbot, strategic calls to action, and mobile-optimized navigation designed to convert visitors into qualified prospects.",
    image: "/projects/the-shield-corporation.png",
    spanClass: "md:col-span-6",
    aspectClass: "aspect-[16/10]",
    link: "https://shield-corpration.vercel.app/",
    linkLabel: "Live website",
    year: "2026",
  },
];

export const journalEntries: JournalEntry[] = [
  {
    id: "journal-1",
    title: "Designing Modern SaaS Interfaces with React",
    category: "React",
    image: "https://images.unsplash.com/photo-1547953571-5f26253d8c4a?auto=format&fit=crop&q=80&w=400",
    readTime: "5 min read",
    date: "May 2026",
    summary: "Reflecting on organic component structures, interactive layouts, and high-performance design paradigms with React & Tailwind CSS.",
  },
  {
    id: "journal-2",
    title: "Why Motion Design Changes User Experience",
    category: "UX/UI",
    image: "https://images.unsplash.com/photo-1618005198143-e52834644027?auto=format&fit=crop&q=80&w=400",
    readTime: "4 min read",
    date: "April 2026",
    summary: "Exploring the emotional connection of custom easing curves, micro-interactions, and visual feedback that completely redefine UI touchpoints.",
  },
  {
    id: "journal-3",
    title: "Building Scalable Platforms as a Student Developer",
    category: "Engineering",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=400",
    readTime: "6 min read",
    date: "March 2026",
    summary: "A transparent look into state systems, database architecture decisions, and scaling full stack apps under constrained compute environments.",
  },
  {
    id: "journal-4",
    title: "Creating Premium UI Experiences with Tailwind CSS",
    category: "Design System",
    image: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&q=80&w=400",
    readTime: "5 min read",
    date: "February 2026",
    summary: "Uncovering how design system utilities combine for polished atmospheric dark layouts, custom HSL properties, and custom animations.",
  },
];

export const explorations: Exploration[] = [
  {
    id: "exp-1",
    title: "Exploration 01",
    image: "https://images.unsplash.com/photo-1604871000636-074fa5117945?auto=format&fit=crop&q=80&w=600",
    rotation: "rotate-2",
    details: "An experiment in high-contrast typographic noise and raw spatial depth.",
  },
  {
    id: "exp-2",
    title: "Liquid Flow 02",
    image: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?auto=format&fit=crop&q=80&w=600",
    rotation: "-rotate-3",
    details: "Vibrant high-contrast fluid simulation exploring canvas turbulence and friction.",
  },
  {
    id: "exp-3",
    title: "Deep Space 03",
    image: "https://images.unsplash.com/photo-1550684847-75bdda21cc95?auto=format&fit=crop&q=80&w=600",
    rotation: "rotate-3",
    details: "A series of elegant obsidian material meshes and matte micro-shaders.",
  },
  {
    id: "exp-4",
    title: "Glassmorphism 04",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&q=80&w=600",
    rotation: "-rotate-2",
    details: "High-refraction material investigations simulating heavy glass blocks in browser environments.",
  },
  {
    id: "exp-5",
    title: "Canvas Play 05",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=600",
    rotation: "rotate-1",
    details: "Generative organic pigment layering emphasizing negative space and flow.",
  },
  {
    id: "exp-6",
    title: "Brutalist Neon 06",
    image: "https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?auto=format&fit=crop&q=80&w=600",
    rotation: "-rotate-1",
    details: "Crisp architectural constructs animated with vibrant glowing lightbars.",
  },
];
